### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by weihao86233531** [DetectionTeamUCAS/FCOS_Tensorflow#13]
Thank you for your code.I have a problem.when I train my dataset,I meet this error:

UnknownError (see above for traceback): IndexError: too many indices for array
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "../libs/detection_oprations/fcos_target.py", line 101, in get_fcos_target_batch
    gt_target = fcos_target(gtboxes_batch[i, :, :], img_batch[i, :, :, :], fm_size_list)

  File "../libs/detection_oprations/fcos_target.py", line 36, in fcos_target
    center[:, :, 0] = 0

IndexError: too many indices for array

	 [[node build_loss/fcos_target/PyFunc (defined at ../libs/networks/build_whole_network.py:210)  = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT], token="pyfunc_10", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Cast, get_batch/batch:1, build_loss/fcos_target/PyFunc/input_2)]]

**Comment by yangxue0827** [comment]
The latest code has been updated, and the performance has been greatly improved.
